spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 10MB
      file-size-threshold: 0
  web:
    resources:
      chain:
        compressed: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    open-in-view: false
  datasource:
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
server:
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_DEMO
    encoding:
      charset: UTF-8
      enabled: true
      force: true
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
springdoc:
  paths-to-match:
    - /api/v1/**
decorator:
  datasource:
    p6spy:
      logging: slf4j
      multiline: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: sa
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
  h2:
    console:
      enabled: true
server:
  port: 8080
sentry:
  logging:
    enabled: false
management:
  endpoint:
    health:
      enabled: false
  endpoints:
    enabled-by-default: false
environment:
  app:
    test: test
---
spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
server:
  port: 8080
sentry:
  dsn: https://7bb0a4fc0ddc4803998ee772401e3cfc@o368486.ingest.sentry.io/5197118
  environment: sandbox
  server-name:
  traces-sample-rate: 1.0
environment:
  app:
    test: test
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
server:
  port: 8000
sentry:
  dsn: https://7bb0a4fc0ddc4803998ee772401e3cfc@o368486.ingest.sentry.io/5197118
  environment: prod
  server-name:
  traces-sample-rate: 1.0
environment:
  app:
    test: test
