spring:
  profiles:
    active: local
  servlet:
    multipart:
      enabled: false
  web:
    resources:
      chain:
        compressed: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_batch_fetch_size: 1000
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
server:
  port: 8000
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    session:
      cookie:
        name: JSESSIONID_DEMO
    encoding:
      charset: UTF-8
      enabled: true
      force: true
decorator:
  datasource:
    p6spy:
      logging: slf4j
      multiline: true
springdoc:
  api-docs:
    enabled: false
sentry:
  dsn: https://3f180e3ef4724309ada7d86417762b1f@sentry.cubewiz.net/11
  traces-sample-rate: 1.0
cloud:
  aws:
    stack:
      auto: false
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:mydb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;
    username: sa
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
server:
  port: 8080
sentry:
  logging:
    enabled: false
environment:
  app:
    test: test
---
spring:
  config:
    activate:
      on-profile: sandbox
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
springdoc:
  api-docs:
    enabled: true
  paths-to-match:
    - /api/v1/**
sentry:
  environment: sandbox
environment:
  app:
    test:
---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
sentry:
  environment: qa
environment:
  app:
    test: test
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url:
    username:
    password:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
sentry:
  environment: prod
environment:
  app:
    test: test
