name: 'Build Gradle'
description: 'Build gradle'

runs:
  using: 'composite'
  steps:
    - run: |
        echo "gradle build"
        chmod +x gradlew
        ./gradlew build --no-daemon --exclude-task test -Dspring.profiles.active=dev
      shell: bash
