name: Deploy

on:
  push:
    branches: [ main, RC/** ]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'gradle'

      - uses: ./.github/actions/build-gradle
