name: Test

on: push
#    branches-ignore: [main, RC/**]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@main
        with:
          gradle-version: current
          arguments: |
            build
            --no-daemon
            --exclude-task test
            -Dspring.profiles.active=dev

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          if_mention: always
          fields: repo,message,commit,author,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
