name: Test

on:
  push:
    branches-ignore: [ main, RC/** ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      CI: true

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-version: [ 17 ]

    steps:
      - uses: actions/checkout@main

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Cache Gradle
        uses: actions/cache@main
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: ./.github/actions/build-gradle
